### ISSUE TITLE
I only get a raster full of 1s

### ISSUE THREAD

**Issue by pcav** [miguel-reginaldo/Slicer#2]
I sliced a DTM at 500 m steps, from 0 to 2000, nut I get a map of 1s (plus the extreme values, not NULLs, see other ticket)

**Comment by miguel-reginaldo** [comment]
Perdoe-me, pois não consegui compreender direito o seu posicionamento com relação à esta questão. Meu inglês é muito ruim...

**Comment by miguel-reginaldo** [comment]
Forgive me, because I could not correctly understand its position with respect to this issue. My English is very bad ...

**Comment by pcav** [comment]
The output is made up of value=1 only, not the expected results.

**Comment by miguel-reginaldo** [comment]
Please check the minimum and maximum values of your DTM are in the range (slice) 0-500, ie in class 1 and the output file will only return 1. If so is correct, otherwise try to send this raster to me.

**Comment by pcav** [comment]
My data go from -3 to >2000
