### ISSUE TITLE
NULLs should be NULL

### ISSUE THREAD

**Issue by pcav** [miguel-reginaldo/Slicer#3]
When sliced, NULLs are put back to they real value  (-3.4028234663852886e+38), not NULLified. This is inconvenient for the user.

**Comment by miguel-reginaldo** [comment]
Already managed to solve the problem, I hope to publish a new version of the plugin until tomorrow. Thanks for the contribution!

**Comment by miguel-reginaldo** [comment]
Problem solved with Version 1.1
