### ISSUE TITLE
Please add file extension to the output

### ISSUE THREAD

**Issue by pcav** [miguel-reginaldo/Slicer#4]
By default, the output file has no extension (e.g. .tif) unless the user explicitely type it.
Please let the plugin add it automatically.

**Comment by miguel-reginaldo** [comment]
Strange ??
Automatically the output file is sent to the line of text with the extension \* .tif, without the need to enter it. You can check again, because this is not happening on my machine. I'll check on other equipment.

**Comment by pcav** [comment]
I'm on Debian. I'll check again with the new version once you publish it.
