### ISSUE TITLE
Uncompressed output

### ISSUE THREAD

**Issue by pcav** [miguel-reginaldo/Slicer#5]
The output is apparently uncompressed; this results in a waste of space. Please add a compression by default.

**Comment by miguel-reginaldo** [comment]
I'll work this suggestion.

**Comment by miguel-reginaldo** [comment]
Problem solved ... It is possible to compress the output rarster.
Meloramos the code and the processamente giant raster became much faster.

Version 1.1 of the Slicer plugin is now available.
Now comes with a help button that brings two tutorials.
